/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_neva1ack_toml_TOMLTable */

#ifndef _Included_io_github_neva1ack_toml_TOMLTable
#define _Included_io_github_neva1ack_toml_TOMLTable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_neva1ack_toml_TOMLTable
 * Method:    parseFile
 * Signature: (Ljava/lang/String;)Lio/github/neva1ack/toml/TOMLTable;
 */
JNIEXPORT jobject JNICALL Java_io_github_neva1ack_toml_TOMLTable_parseFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_github_neva1ack_toml_TOMLTable
 * Method:    parse
 * Signature: (Ljava/lang/String;)Lio/github/neva1ack/toml/TOMLTable;
 */
JNIEXPORT jobject JNICALL Java_io_github_neva1ack_toml_TOMLTable_parse
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_github_neva1ack_toml_TOMLTable
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_neva1ack_toml_TOMLTable_free
  (JNIEnv *, jobject);

/*
 * Class:     io_github_neva1ack_toml_TOMLTable
 * Method:    getKeyIn
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_neva1ack_toml_TOMLTable_getKeyIn
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_neva1ack_toml_TOMLTable
 * Method:    isKeyExists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_neva1ack_toml_TOMLTable_isKeyExists
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_github_neva1ack_toml_TOMLTable
 * Method:    getStringIn
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_neva1ack_toml_TOMLTable_getStringIn
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_github_neva1ack_toml_TOMLTable
 * Method:    getBooleanIn
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_neva1ack_toml_TOMLTable_getBooleanIn
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_github_neva1ack_toml_TOMLTable
 * Method:    getIntIn
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_github_neva1ack_toml_TOMLTable_getIntIn
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_github_neva1ack_toml_TOMLTable
 * Method:    getDoubleIn
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_neva1ack_toml_TOMLTable_getDoubleIn
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_github_neva1ack_toml_TOMLTable
 * Method:    getTimestampIn
 * Signature: (Ljava/lang/String;)Lio/github/neva1ack/toml/TOMLTimestamp;
 */
JNIEXPORT jobject JNICALL Java_io_github_neva1ack_toml_TOMLTable_getTimestampIn
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_github_neva1ack_toml_TOMLTable
 * Method:    getArrayIn
 * Signature: (Ljava/lang/String;)Lio/github/neva1ack/toml/TOMLArray;
 */
JNIEXPORT jobject JNICALL Java_io_github_neva1ack_toml_TOMLTable_getArrayIn
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_github_neva1ack_toml_TOMLTable
 * Method:    getTableIn
 * Signature: (Ljava/lang/String;)Lio/github/neva1ack/toml/TOMLTable;
 */
JNIEXPORT jobject JNICALL Java_io_github_neva1ack_toml_TOMLTable_getTableIn
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
