/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_neva1ack_toml_TOMLArray */

#ifndef _Included_io_github_neva1ack_toml_TOMLArray
#define _Included_io_github_neva1ack_toml_TOMLArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_neva1ack_toml_TOMLArray
 * Method:    getSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_github_neva1ack_toml_TOMLArray_getSize
  (JNIEnv *, jobject);

/*
 * Class:     io_github_neva1ack_toml_TOMLArray
 * Method:    getStringAt
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_neva1ack_toml_TOMLArray_getStringAt
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_neva1ack_toml_TOMLArray
 * Method:    getBooleanAt
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_neva1ack_toml_TOMLArray_getBooleanAt
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_neva1ack_toml_TOMLArray
 * Method:    getIntAt
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_io_github_neva1ack_toml_TOMLArray_getIntAt
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_neva1ack_toml_TOMLArray
 * Method:    getDoubleAt
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_neva1ack_toml_TOMLArray_getDoubleAt
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_neva1ack_toml_TOMLArray
 * Method:    getTimestampAt
 * Signature: (I)Lio/github/neva1ack/toml/TOMLTimestamp;
 */
JNIEXPORT jobject JNICALL Java_io_github_neva1ack_toml_TOMLArray_getTimestampAt
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_neva1ack_toml_TOMLArray
 * Method:    getArrayAt
 * Signature: (I)Lio/github/neva1ack/toml/TOMLArray;
 */
JNIEXPORT jobject JNICALL Java_io_github_neva1ack_toml_TOMLArray_getArrayAt
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_neva1ack_toml_TOMLArray
 * Method:    getTableAt
 * Signature: (I)Lio/github/neva1ack/toml/TOMLTable;
 */
JNIEXPORT jobject JNICALL Java_io_github_neva1ack_toml_TOMLArray_getTableAt
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
