/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_neva1ack_toml_TOMLTimestamp */

#ifndef _Included_io_github_neva1ack_toml_TOMLTimestamp
#define _Included_io_github_neva1ack_toml_TOMLTimestamp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_neva1ack_toml_TOMLTimestamp
 * Method:    getYear
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_github_neva1ack_toml_TOMLTimestamp_getYear
  (JNIEnv *, jobject);

/*
 * Class:     io_github_neva1ack_toml_TOMLTimestamp
 * Method:    getMonth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_github_neva1ack_toml_TOMLTimestamp_getMonth
  (JNIEnv *, jobject);

/*
 * Class:     io_github_neva1ack_toml_TOMLTimestamp
 * Method:    getDay
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_github_neva1ack_toml_TOMLTimestamp_getDay
  (JNIEnv *, jobject);

/*
 * Class:     io_github_neva1ack_toml_TOMLTimestamp
 * Method:    getHour
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_github_neva1ack_toml_TOMLTimestamp_getHour
  (JNIEnv *, jobject);

/*
 * Class:     io_github_neva1ack_toml_TOMLTimestamp
 * Method:    getMinute
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_github_neva1ack_toml_TOMLTimestamp_getMinute
  (JNIEnv *, jobject);

/*
 * Class:     io_github_neva1ack_toml_TOMLTimestamp
 * Method:    getSecond
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_github_neva1ack_toml_TOMLTimestamp_getSecond
  (JNIEnv *, jobject);

/*
 * Class:     io_github_neva1ack_toml_TOMLTimestamp
 * Method:    getMilliSecond
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_github_neva1ack_toml_TOMLTimestamp_getMilliSecond
  (JNIEnv *, jobject);

/*
 * Class:     io_github_neva1ack_toml_TOMLTimestamp
 * Method:    isZeroedTime
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_neva1ack_toml_TOMLTimestamp_isZeroedTime
  (JNIEnv *, jobject);

/*
 * Class:     io_github_neva1ack_toml_TOMLTimestamp
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_neva1ack_toml_TOMLTimestamp_free
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
